packages:
  - "."

patchedDependencies:
  wouter@3.7.1: patches/wouter@3.7.1.patch

overrides:
  "@esbuild-kit/core-utils>esbuild": 0.25.12
  katex: 0.18.2
  postcss-selector-parser: 7.1.6
  proxy-addr: 2.0.8
  source-map-js: 1.2.2

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

allowBuilds:
  "@tailwindcss/oxide": true
  esbuild: true
